### ISSUE TITLE
Types of Data Visualization Projects

### ISSUE THREAD

**Issue by jacksonh2** [mschermann/data_viz_reader#1241]
In this section of "How to run a data viz project" chapter, our group would like to describe the the various types of data viz projects, in terms of the purposes of these projects. For example, a data viz project that's developed for a board meeting needs to be straight to the point and easy to understand, whereas a project that's developed for the marketing team can be much more versatile in terms of design and information carried. Furthermore, there are also viz projects for scientific research, viz project for political purposes etc.

**Comment by jymhe120** [comment]
I have done some research and found that there are two visualization projects for different purposes: 1. For understanding 2. For persuasion. The purpose of the first type is to present the whole data set in a direct and unbiased way, quite similar to what we've discussed in class last Thursday. For instance, we center all the data on the x and y-axis to indicate that we are showing all the data. The goal for the second type is to influence users to make certain decisions. This is similar to the Chicago mayor project we have done. We need to decide whether we should show the whole data or just the trend. 

This link goes in depth in this issue and contains excellent visualizations:
https://medium.com/bucknell-hci/a-detail-implementation-of-two-approaches-to-data-visualization-design-for-understanding-and-f2ae307b360

**Comment by phoenixren** [comment]
For the types of data visualization projects, there are some different topics and directions we can explore in terms of the two purposes of visualizations that Maria mentioned. We can look for examples mainly in academic for the persuasion purpose such as using data visualization to test or show proof of a hypothesis in scientific research. As for understanding, we can find examples in business, where dash-boards are heavily used for understanding and tracking the key business indicators.

**Comment by JinjinJanelle** [comment]
I think we can divide the types of data viz projects into two categories: to inform and to persuade.

For the 'to inform' type, the main goal is to deliver knowledge effectively to the audience. The situations can be a board meeting, a earnings call, a monthly sales report and etc. Data vizs are used to present facts here. It is more appropriate to display a single number or simple and basic charts for easier understanding, instead of complex charts with advanced features. Little background of the data presented is needed here.

For the 'to persuade' type, the main goal is to prove a point to the audience and trigger attention, change or decision making. The situations can be a proposal of business decisions, a meeting to find out why sales drops or an advocate of energy saving actions. Data vizs are used to find reasons behind facts, or compare different situations. The charts are more complicated and much background information is needed to the data presented. It is very import to tell a story with logic, explaining from begining to end carefully.

**Comment by jacksonh2** [comment]
Was able to merge what everyone said into the section of the new chapter.

**Comment by mschermann** [comment]
@jacksonh2 Why is this still open?

**Comment by jacksonh2** [comment]
done
