### ISSUE TITLE
2.1 unclear symbol in text

### ISSUE THREAD

**Issue by phoenixren** [mschermann/data_viz_reader#835]
In the last paragraph of this section, there is a (???) at end of a sentence. Seems like a missing citation need to work on?

**Comment by kthang** [comment]
The entire section is:

Visualization can make sense of information by helping to find relationships in the data and support (or disproving) ideas about the data. (???) shares some examples and common uses of information visualization, such as:

From this passage, it is also unclear what "shares some examples".  ??? might also refer to the original source of the examples.

**Comment by rlwy** [comment]
Issue resolved in PR #1069 

Looking up the content of the text, I think the unclear symbol in text is due to an error in the citation tag used. The original code uses `@info_viz`. The right citation tag to use should be `@lawfraud`, as is in the .bib file. If you browse to the url in the reference file, you can see that the content of the page is the same as the one in the reader project, which talks about the four reasons why graph visualization is such a powerful tool:
- It’s *intuitive* – presenting a graph as a node-link structure instantly makes sense, even to people who’ve never worked with graphs before.
- It’s *fast* – our brains are great at spotting patterns, but only when data is presented in a tangible format. Armed with visualization, we can spot trends and outliers very effectively.
- It’s *flexible* – the world is densely connected, so as long as there’s an interesting relationship in your data somewhere, you’ll find value in a graph visualization.
- It’s *insightful* – exploring graph data interactively allows users to gain deeper knowledge, understand context and ask more questions, compared to static visualization or just looking at raw data.
